
# An Example of how you can get a secret for kubernetes out of an vault property
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  # Name of the resource, should be identical to the target name
  name: artifact-store-credentials
spec:
  # Interval, of how often the operator will check for an update of the property
  refreshInterval: "15s"
  # Config-Parameter for the SecretStore
  secretStoreRef:
    name: vault-connector
    kind: SecretStore
  target:
    # Name of the finished secret, should be identical to the ExternalSecret name (just for better understanding)
    name: artifact-store-credentials
  data:
  # Name of the field inside the kubernetes secret's data
  - secretKey: accessKeyID
    remoteRef:
      # Path inside the secret engine
      key: artifactStore
      # Key of the property value
      property: accessKeyID
  # Name of the field inside the kubernetes secret's data
  - secretKey: secretAccessKey
    remoteRef:
      # Path inside the secret engine
      key: artifactStore
      # Key of the property value
      property: secretAccessKey