apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-connector
spec:
  provider:
    vault:
      # URL to the vault server (this is the local dns entry to the service)
      # this works, if your service ist named vault in the namespace vault
      # See https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/ for documentation of internal dns
      server: http://vault.vault.svc.cluster.local:8200
      # Path of the secret engine
      path: loki
      # version of the secret engine
      version: v2
      auth:
        kubernetes:
          # Path of the kubernetes authentication (kubernetes is default)
          mountPath: kubernetes
          # Vault role for your ServiceAccount Entity
          role: loki-reader
          # Reference to the ServiceAccount
          serviceAccountRef:
            name: vault-accessor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  # Change name if needed, but be aware, that the Secret Store resource links to this object
  name: vault-accessor